### ISSUE TITLE
Do you own github.com/virginiatech?

### ISSUE THREAD

**Issue by amandafrench** [filler/universities-on-github#26]
We are looking into creating a GitHub organization for Virginia Tech, but someone (maybe you?) has already created http://github.com/virginiatech. Can you give me access to the project, at least? Or any info you have?

**Comment by amitkumarj441** [comment]
Alright @amandafrench ! But i just gone through the above link and it's showing that there is no repository associated with Virginiatech. So if you want to create a Github organization(if urgent), then you can ask on github help to close the older one, and then after you can create a new one given that in case of no response to this comment or if he is not the owner of this organization!
Please let me know in case of any further query.

**Comment by filler** [comment]
Hello!  I do not own it, @amandafrench.  However @amitkumarj441 is right in that a GitHub Support Request should accomplish what you're after.  

Cheers!
